### ISSUE TITLE
BLE info

### ISSUE THREAD

**Issue by electro-logic** [arsya/sony_camera_ble_remote#1]
Hello,

Before connecting the ESP32, you need to set the encryption level with:

BLEDevice::setEncryptionLevel(ESP_BLE_SEC_ENCRYPT);

or something equivalent in python.

Cheers

**Comment by arsya** [comment]
Thanks for your information. Do you have any reference or sample code (in C or python) that I can learn from?
As for micropython I read from the docs, it says:
https://docs.micropython.org/en/latest/library/bluetooth.html#pairing-and-bonding
... To support bonding, an application must implement the _IRQ_GET_SECRET and _IRQ_SET_SECRET events.
Note: This is currently only supported when using the NimBLE stack on STM32 and Unix (**not ESP32**).

**Comment by electro-logic** [comment]
Hello,
Have a look at BLE.config() with micropython, although I suggest you to create a quick prototype with Arduino/ESP32 first where you can use the BLEDevice class. Try to reset the network on your camera before pairing, if something got wrong.

**Comment by arsya** [comment]
Okay, I will get more info about BLE.config(). Thanks.
